---
- hosts: "{{ hosts }}"
  become: true
  tasks:
  - name: Instalar apache
    package:
      name: httpd
      state: latest
    tags: instalar
  - name: Inicio servicio y configuramos arranque
    service:
      name: httpd
      state: started
      enabled: yes
    tags: instalar
  - name: Creamos welcome page
    file:
      path: /var/www/html/index.html
      state: touch
    tags: configuracion
  - name: Añadimos contenido al fichero
    copy:
      content: "Hola"
      dest: /var/www/html/index.html
    tags: configuracion
  - name: Desisntalar apache
    package:
      name: httpd
      state: absent
    tags: [never,desinstalar]